spring:
  data:
    redis:
      host: 146.56.115.136
      port: 6379
      password: hello
  datasource:
    hikari:
      maximum-pool-size: 5
      auto-commit: true
      idle-timeout: 30000
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:testdb
      username: sa

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

